modName=Plasmo Voice
modId=plasmovoice
modGroup=su.plo.voice

useModGroupForPublishing=true
autoUpdateBuildScript=false

minecraftVersion=1.7.10
forgeVersion=10.13.4.1614
customArchiveBaseName=plasmovoice-forge-1.7.10

channel=stable
mappingsVersion=12
remoteMappings=https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/

developmentEnvironmentUserName=SacotoDayle

enableModernJavaSyntax=modern
enableGenericInjection=true

usesMixins=false

gtnh.modules.codeStyle=false